name: 'Clients Workflow (Whatif)'

on:
  workflow_call:
    inputs:
      labels:
        required: true
        type: string
      files:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  LOCATION: "southcentralus"

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write
  security-events: write

jobs:
  client-job:
    name: 'Client Whatif'
    runs-on: ubuntu-latest
    if: contains(join(fromJSON(inputs.labels), ' '), 'client-')
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3

      # Authenticate to Az CLI using OIDC
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run client what-if deployments
        run: |
          labels=$(echo '${{ inputs.labels }}' | jq -r '.[]' | grep '^client-' || true)
          files=$(echo '${{ inputs.files }}' | jq -r '.[]')

          for label in $labels; do
            client_name="${label#client-}"
            bicep_file="src/iac/az-controllers/azure-services/client/${client_name}.bicep"
            param_file="src/params/dev/${client_name}.bicepparam"

            if grep -q "$bicep_file" <<< "$files" || grep -q "$param_file" <<< "$files"; then
              echo "🚀 Running What-If for client: $client_name"

              # Lint
              az bicep build --file "$bicep_file"

              # Validate
              az deployment sub validate \
                --name validate-${{ github.run_id }}-$client_name \
                --template-file "$bicep_file" \
                --parameters "$param_file" \
                --parameters location=$LOCATION \
                --location $LOCATION

              # What-if
              az deployment sub what-if \
                --name whatif-${{ github.run_id }}-$client_name \
                --template-file "$bicep_file" \
                --parameters "$param_file" \
                --parameters location=$LOCATION \
                --location $LOCATION > whatif-$client_name

              # Post results
              body=$(cat <<EOF
              <details>
              <summary>## What-If ($client_name)</summary>
              \`\`\`
              $(cat whatif-$client_name)
              \`\`\`
              </details>
              EOF
              )
            else
              echo "❌ ERROR: Label '$label' given but no matching file changes for $client_name"
              exit 1
            fi
          done