name: 'Azure Bicep Create and Deploy - Client Services'

on:
  workflow_call:
    inputs:
      labels:
        required: true
        type: string
      files:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      TALOS_KEYVAULT_SECRETS:
        required: true

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: contains(join(fromJSON(inputs.labels), ' '), 'client-')
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Log into Azure
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Prepare Key Vault secrets
      - name: Create talosSecrets.json and escape it
        shell: bash
        run: |
          echo '${{ secrets.TALOS_KEYVAULT_SECRETS }}' > talosSecrets.json
          TALOS_SECRETS_ESCAPED=$(cat talosSecrets.json | jq -c .)
          echo "::add-mask::$TALOS_SECRETS_ESCAPED"
          echo "TALOS_SECRETS_ESCAPED=$TALOS_SECRETS_ESCAPED" >> $GITHUB_ENV

      # Deploy all client files from labels
      - name: Deploy Clients
        shell: bash
        run: |
          echo "🚀 Deploying shared services"