name: 'Shared Workflow (Whatif)'

on:
  workflow_call:
    inputs:
      labels:
        required: true
        type: string
      files:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
env:
  LOCATION: "southcentralus"

permissions:
  id-token: write
  contents: read
  actions: read
  pull-requests: write
  security-events: write

jobs:
  shared-job:
    name: 'Shared Whatif'
    runs-on: ubuntu-latest
    if: |
      contains(fromJSON(inputs.labels), 'shared') &&
      (
        contains(join(fromJSON(inputs.files), ' '), 'src/iac/az-controllers/azure-services/shared/') ||
        contains(join(fromJSON(inputs.files), ' '), 'src/params/dev/main.bicepparam')
      )
    steps:
      - uses: actions/checkout@v3

      # Authenticate to Az CLI using OIDC
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Lint
      - name: Bicep Lint (Shared)
        uses: Azure/cli@v2
        with:
          inlineScript: az bicep build --file ./src/iac/az-controllers/azure-services/shared/main.bicep

      # Validate
      - name: Bicep Validate (Shared)
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az deployment sub validate \
              --name validate-${{ github.run_id }} \
              --template-file ./src/iac/az-controllers/azure-services/shared/main.bicep \
              --parameters ./src/params/dev/main.bicepparam \
              --parameters location=$LOCATION \
              --location $LOCATION

      # What-if
      - name: What-If (Shared)
        id: whatif-shared
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az deployment sub what-if \
              --name whatif-shared-${{ github.run_id }} \
              --template-file ./src/iac/az-controllers/azure-services/shared/main.bicep \
              --parameters ./src/params/dev/main.bicepparam \
              --parameters location=$LOCATION \
              --location $LOCATION > whatif-shared

      # Publish What-If to PR
      - name: Publish What-If (Shared)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('whatif-shared', 'utf8');
            const body = `## What-If (Shared)\n\n\`\`\`\n${output}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
