#
# Dependabot configuration
#

# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/getting-started/dependabot-quickstart-guide

version: 2
updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily