name: 'Shared Workflow'

on:
  workflow_call:
    inputs:
      labels:
        required: true
        type: string
      files:
        required: true
        type: string

jobs:
  shared-job:
    name: 'Shared Tests'
    runs-on: ubuntu-latest
    if: |
      contains(fromJSON(inputs.labels), 'shared') &&
      (
        contains(join(fromJSON(inputs.files), ' '), 'src/iac/az-controllers/azure-services/shared/') ||
        contains(join(fromJSON(inputs.files), ' '), 'src/params/dev/main.bicepparam')
      )
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "✅ Running SHARED deployment in $LOCATION..."
